### ISSUE TITLE
Sandbox error: The remote name could not be resolved: 'app.reapit.cloud'

### ISSUE THREAD

**Issue by teoAmico** [reapit/foundations#11168]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
We're currently keep getting error popups with the same issue in our sandbox: "The remote name could not be resolved: 'app.reapit.cloud'"

**Detail and or supporting links and screenshots**
Reapit Version: 12.182.2

Type: System.Net.WebException
Message: The remote name could not be resolved: 'app.reapit.cloud'

Stack Trace
   at RPS.Business.Http.HttpHelper.ExecuteWebDAVRequest(String path, String method, String depthHeader, String requestBody, Boolean throwException, Int32& retryCount, Boolean setProxyCredentials, Int32 connectionFailureRetryCount)
   at RPS.Business.Http.HttpHelper.GetDirectoryInfo(RPSDirInfo rpsDirInfo, Boolean throwException)
   at RPS.Business.Http.HttpHelper.GetDirectoryInfo(RPSDirInfo rpsDirInfo, Boolean throwException)
   at RPS.Business.Http.HttpHelper.GetDirectoryInfo(String path, Boolean getOfficeSubFolderInfo, Boolean throwException)
   at RPS.Business.FileSystem.FileSystemManager.GetDirectoryInfo(String path, Boolean getOfficeSubFolderInfo, Boolean throwException)
   at RPS.Business.Dynamic.DynamicResourceLoader.GetResourceFileInfo(String fileName, Boolean checkOfficeSubFolders)
   at RPS.Business.Dynamic.DynamicResourceLoader.GetInstance(String fileName, Object[] args, String className, Boolean checkOfficeSubFolders, Boolean bubbleException)
   
   
   Matteo A.
   Goodlord

**Comment by AshDeeming** [comment]
Hi @teoAmico 
Please could you confirm that you have 

Uninstalled any previous RPS software via programs
Then
Please could you delete the current & previous versions in the registry:

Press Windows Key + R: This key combination opens the Run dialog box.
Type “regedit”: In the Run dialog box, type “regedit” (without quotes) into the text field.
Press Enter or click OK: Hit Enter on your keyboard or click OK to launch the Registry Editor.
Find CurrentVersion & PreviousVersion - right click both & delete.


Then finally relaunch RPS via the below link in Edge browser - we've seen issues when chrome is used. 
[https://updates.reapit.com/awsdev/publish.htm](https://url.uk.m.mimecastprotect.com/s/grLJCzp8gSGVD5mfwxUwL?domain=updates.reapit.com)

**Comment by teoAmico** [comment]
Hi @AshDeeming 

Thank you, It's working now.

Matteo A.
Goodlord
