### ISSUE TITLE
Cannot install new developer version

### ISSUE THREAD

**Issue by jwr8385** [reapit/foundations#11171]
Hello,

I get the error - application cannot be installed.   Please find below the error report:

PLATFORM VERSION INFO
	Windows 			: 10.0.22631.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.9176.0 built by: NET481REL1LAST_B
	clr.dll 			: 4.8.9241.0 built by: NET481REL1LAST_C
	dfdll.dll 			: 4.8.9176.0 built by: NET481REL1LAST_B
	dfshim.dll 			: 10.0.22621.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/jwr83/Downloads/RPS%20(3).application

IDENTITIES
	Deployment Identity		: RPS - Developer, Version=12.182.1.0, Culture=neutral, PublicKeyToken=30ab95f2beb2c8f4, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\jwr83\Downloads\RPS (3).application resulted in exception. Following failure messages were detected:
		+ Deployment and application do not have matching security zones.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [28/05/2024 09:44:36] : Activation of C:\Users\jwr83\Downloads\RPS (3).application has started.
	* [28/05/2024 09:44:36] : Processing of deployment manifest has successfully completed.
	* [28/05/2024 09:44:36] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [28/05/2024 09:44:36] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available

**Comment by jwr8385** [comment]
Thanks Ash - It was chrome.  No problems with Edge so all sorted.
