### ISSUE TITLE
RPS Developer Edition - No company with the code SBOX exists error

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#5022]
**Summary**
We subscribed to 1 user of Developer Edition of Agency Cloud.
When i logged to RPS Developer Edition, I've got an error like below
https://drive.google.com/file/d/1pAG3AWMKrLRsJY0oYZE9j79k9wPCXc9f/view

**Detail and or supporting links and screenshots**

```
The following exception was encountered at 04:40:43 on 16/09/2021

Company: 
Office: 
User: 
RPS Version: 12.132.2

Message: An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated (No company with the code SBOX exists)

Stack Trace
   at RPS.AppSettings.TryLoginWebServiceAuthentication(Boolean reapitConnect, String& userName, String password, AppControl& appControl)
   at RPS.AppSettings.AuthenticateNegotiator(Boolean reapitConnect, String& userName, Boolean gotPassword, String password, AppControl& appControl)
   at RPS.UI.LoginPageBase.DoLogin_Background(Object sender, DoWorkEventArgs e)


Error Log Entry
16/09/2021 04:40:43    v:    o:    n:    u:utilihub-reapit\devops    m:utilihub-reapit    w:Windows 10 Enterprise    trace:at RPS.AppSettings.TryLoginWebServiceAuthentication(Boolean reapitConnect, String& userName, String password, AppControl& appControl)    message:An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated (No company with the code SBOX exists)
```

**Comment by plittlewood-rpt** [comment]
Hi @buonzz - can you confirm if you have any other installations of Agency Cloud on your machine please? That error usually only occurs when a real customer build of Agency Cloud has been launched (instead of Developer Edition)

**Comment by buonzz** [comment]
hi, 
I dont have any other installation in my machine. Holly is already assisting with me on this. So we can close this.
Thanks
